name: Check links for modified files in PR
on:
  pull_request: 
    branches: [ master ]

jobs:
  Broken_Link_Checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: "markdown"
          use-quiet-mode: "yes"
          config-file: ".github/brokenlinks-config.json"
          check-modified-files-only: "yes"
