name: Weekly link checker
on:
  push:
    branches:
    - master
  schedule:
    # Run at midnight every sunday
    - cron: "0 0 * * 0"

jobs:
  weekly_broken_Link_Checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/workflows/brokenlinks-config.json"

      - name: Create Issue
        if: failure()
        uses: JasonEtco/create-an-issue@v2.9.1
        env: 
          GITHUB_TOKEN: ${{ github.token }}
        with:
          filename: .github/action-issue-template.md
          assignees: tamimigithub