name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your first issue! We will get to your issue as soon as possible. In the meantime, you can post about this on our community website https://solace.community/ for faster response'
        pr-message: 'Thanks for your first contribution to our codelabs! We will get notified about your PR and will get to it as soon as possible. In the meantime, make sure there is a technical reviewer for your codelab to review the technical content. Also, make sure to join our community on https://solace.community/ and promote your codelab there! 👋'
